lib/duktape: Use python2 instead of python
unikraft/lib-duktape pull request #4
Opened 2023-07-15 13:53 UTC by DovydasVad

Using only `python` might be problematic, as it might refer to `python3`, but the current version of `ducktape` uses `python2`.

2023-07-15 14:19 UTC, RaduNichita requested changes
Please change your commit message to be:

```console
`Makefile.uk`: Change python version to be python2.

This is needed for the `tools/configure.py` to be interpreted with `python2`.
```

2023-07-15 20:53 UTC, RaduNichita requested changes
Remove the tick from the commit message. So it should be:

```
 Makefile.uk: Change python version to be python2. 
```

instead of 

```
 Makefile.uk`: Change python version to be python2. 
```

2023-07-16 06:19 UTC, razvand requested changes
Remove dot at the end of the first commit line. In the first commit line, use `Python` and `Python2` instead of `python`. Keep it lower case for the second commit line.

The second commit line is incomplete. Mention why Python 2 is required. Maybe say:

"""
`tools/configure.py` uses Python2 syntax. If only using `python` as the command, this may cause the use of Python3, and that results in syntax errors. So this commit enforces the use of `python2`.
"""

Sign-off your commit.

See more info on [submitting changes](https://unikraft.org/docs/contributing/submitting-changes/).

2023-07-21 07:14 UTC, StefanJum requested changes
Thanks @DovydasVad. Please remove the dot at the end of the commit message.
Also state that the `configure.py` script does not work with python3, and it will fail on systems where python3 is the default one.

2023-07-25 19:00 UTC, StefanJum requested changes
Thank you @JoachimBose.

Please wrap the commit messages to ~50 character per line and the commit descriptions to ~80 characters per line.

2023-07-27 11:13 UTC, StefanJum approved these changes
Thank you @DovydasVad, this looks fine now.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-30 13:22 UTC, RaduNichita approved these changes
Nice job, @DovydasVad 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-05 06:38 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 14:19 UTC, closed without merging